version: '3'

services:
  primes_api:
    build: ./
    container_name: primes_api
    ports:
      -3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - primes_network
    depends_on:
      primes_db
  primes_db:
    image: postgres:14.2-alpine
    container_name: primes_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - primes_network
    volumes:
      - pg:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.30
    container_name: primes_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: primes@admin.com
      PGADMIN_DEFAULT_PASSWORD: primesadmin
    ports:
      - '3400:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - primes_network
    depends_on:
      - primes_db
  networks:
  derug-network:
    driver: bridge

volumes:
  pg:
    driver: local
  pgadmin:
    driver: local