version: '3'

services:
  primes_api:
    build: ./
    container_name: primes_api
    ports:
      - "${APP_EXTERNAL_PORT:-9000}:9000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - primes_network
    depends_on:
      - primes_db
      - primes_redis
  primes_redis:
    container_name: primes_redis
    image: redis:latest
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - primes_network
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    networks:
      - primes_network
    depends_on:
      - primes_redis
  primes_db:
    image: postgres:14.2-alpine
    container_name: primes_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"
    networks:
      - primes_network
    volumes:
      - pg:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.30
    container_name: primes_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: primes@admin.com
      PGADMIN_DEFAULT_PASSWORD: primesadmin
    ports:
      - '3400:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - primes_network
    depends_on:
      - primes_db
networks:
  primes_network:
    driver: bridge

volumes:
  pg:
    driver: local
  pgadmin:
    driver: local
